'use client';

import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="w-[80%] mx-auto px-4 py-12 overflow-y-auto h-full">
      <div className="mb-6">
        <Link
          href="/"
          className="text-blue-600 hover:text-blue-700 font-medium text-sm flex items-center gap-1"
        >
          <span>←</span> Back to Eval
        </Link>
      </div>
      <div className="mb-10">
        <h1 className="text-4xl font-bold mb-3 text-gray-900">Terms of Service</h1>
        <p className="text-lg text-gray-600">
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </div>

      <div className="max-w-3xl space-y-6 prose prose-gray">
        <section>
          <h2 className="text-2xl font-bold mb-3 text-gray-900">1. Acceptance of Terms</h2>
          <p className="text-gray-700">
            By accessing and using Evvl, you accept and agree to be bound by the terms and provision of this agreement.
            If you do not agree to these terms, please do not use this service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3 text-gray-900">2. Description of Service</h2>
          <p className="text-gray-700">
            Evvl is a client-side web application that allows you to compare AI model outputs from various providers
            including OpenAI, Anthropic, and OpenRouter. The service requires you to provide your own API keys and
            all data is stored locally in your browser.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3 text-gray-900">3. API Keys and Third-Party Services</h2>
          <p className="text-gray-700 mb-3">
            You are responsible for:
          </p>
          <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
            <li>Obtaining and maintaining valid API keys from OpenAI, Anthropic, and/or OpenRouter</li>
            <li>Complying with the terms of service of these third-party providers</li>
            <li>All charges incurred through your use of these third-party APIs</li>
            <li>Keeping your API keys secure and confidential</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3 text-gray-900">4. Data and Privacy</h2>
          <p className="text-gray-700">
            Your API keys, prompts, and AI responses are routed through our servers to reach AI providers.
            API keys are automatically redacted from all server logs. Prompts and responses are never logged.
            We maintain basic operational logs (provider, model, error types) for debugging only. All your
            evaluation results and history are stored locally in your browser only. Your use of this service
            is subject to our Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3 text-gray-900">5. Disclaimer of Warranties</h2>
          <p className="text-gray-700">
            Evvl is provided "as is" without any warranties, express or implied. We do not warrant that the service
            will be uninterrupted, secure, or error-free. We are not responsible for the outputs generated by
            third-party AI models.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3 text-gray-900">6. Limitation of Liability</h2>
          <p className="text-gray-700">
            In no event shall Evvl be liable for any indirect, incidental, special, consequential, or punitive
            damages, including without limitation, loss of profits, data, use, or other intangible losses resulting
            from your use of the service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3 text-gray-900">7. Changes to Terms</h2>
          <p className="text-gray-700">
            We reserve the right to modify these terms at any time. Your continued use of the service after any
            such changes constitutes your acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-3 text-gray-900">8. Contact</h2>
          <p className="text-gray-700">
            If you have any questions about these Terms of Service, please contact us through our GitHub repository.
          </p>
        </section>
      </div>
    </div>
  );
}
